# 消息前缀
Prefix: '&b[&dVirtualMenu&b]'
# 两次点击背包物品的间隔，单位毫秒，设置为-1关闭这个功能
AntiSpam: 200
# 是否启用NBT支持，非原版服务端可能出现异常
SupportNBT: true
# 全局语言，菜单设置的语言会覆盖全局设定
Lang:
  NoEnoughMoney: '金钱不足,你需要 {0} 来执行这个动作'
  NoEnoughPoint: '点券不足,你需要 {0} 来执行这个动作'
  NoEnoughtItem: '物品不足,你需要 {0} 个 {1} 来执行这个动作'
  NoEnoughtLevel: '经验不足,你需要到达 {0} 级执行这个动作'
  NoPermission: '权限不足,你需要 {0} 来执行这个命令'
  InternalError: '插件出现内部错误，动作被取消，请联系管理员，错误摘要: {0}'
  
