name: VirtualMenu
main: com.blzeecraft.virtualmenu.VirtualMenuPlugin
version: 0.0.11-dev
softdepend: [PlaceHolderAPI, PlayerPoints, Vault]
depend: [ProtocolLib]
api-version: 1.13
changelog:
- 'Support more types of menus'
- 'Now tell has built-in color code support'
commands:
  virtualmenu:
    description: Main command for VirtualMenu.
    usage: /<command> <reload/info/builder/open>
    aliases: [vm]
    permission: virtualmenu.admin

permissions:
  virtualmenu.admin:
    description: Gives access to all virtualmenu commands
    default: op