name: VirtualMenu
main: com.blzeecraft.virtualmenu.VirtualMenuPlugin
version: 0.0.13-dev
softdepend: [PlaceHolderAPI, PlayerPoints, Vault, LangUtils]
depend: [ProtocolLib]
api-version: 1.13
changelog:
- 'Fixed support for containing colon commands.'
- 'Fix support for 1.7.10'
commands:
  virtualmenu:
    description: Main command for VirtualMenu.
    usage: /<command> <reload/info/builder/open>
    aliases: [vm]
    permission: virtualmenu.admin

permissions:
  virtualmenu.admin:
    description: Gives access to all virtualmenu commands
    default: op