name: VirtualMenu
main: com.blzeecraft.virtualmenu.VirtualMenuPlugin
version: 0.0.15-dev
softdepend: [PlaceHolderAPI, PlayerPoints, Vault, LangUtils]
depend: [ProtocolLib]
api-version: 1.13
changelog:
- 'Fixed support for multi-level menus.'
commands:
  virtualmenu:
    description: Main command for VirtualMenu.
    usage: /<command> <reload/info/builder/open>
    aliases: [vm]
    permission: virtualmenu.admin

permissions:
  virtualmenu.admin:
    description: Gives access to all virtualmenu commands
    default: op